name: Sync Fork

on:
  schedule:
    - cron:  '0 0 * * *'  # Esto ejecutará la acción todos los días a las 12:00 AM.

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master  # Asegúrate de que esto sea la rama que quieres sincronizar.

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/mouredev/roadmap-retos-programacion.git
        git fetch upstream
        git pull upstream master  # Asegúrate de que esto sea la rama que quieres sincronizar.

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master  # Asegúrate de que esto sea la rama que quieres sincronizar.
